[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "10165c136fd9db00d8237df8278464d535bd0213"
os = "macos"

    [[Hwloc.download]]
    sha256 = "d59bcb45f2948ec2d0d31b72f884fbcc6ad2e0b91748725482a391cf5cf83d40"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "efcdf8fb47595eeb48640bf71cbcdebda52c1b93"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "17373697ce7e795663195d565577c76ac9bd97a5f9bcb05bbea04edaa12becbb"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "58eda0ac45cdceb41fc8f4e632c5f0c8de3bd2ac"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "b5c4a431dfd45cced477383329b34816a0b5f71a9a18ba6e02180b4927efa9cb"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0743c72d80b41aad13db06ed8de4038f6f2a331c"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a618d4fb85b48985624dd9001dc88c6569a107c1ca601924c564914b53a15a0f"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7de2cbf06f06a92ec1c982a67c1a392d5069bbb8"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "f8f6e3878e90d238402e95b536f03a74960f8eb617e706c9e2d10413f2048af8"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "69623c6ca8b1a5f0df425741d11d4f63ba998f98"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "7943fbf2bbf4d23c48924bf126f4b4fe1b38dd9b79aef24e2b64ad04d105c4eb"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "196928c419b4acaa19faa3ded878a759cd33a93c"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "7b1a229c4697d4582f878ea508906389894d6418be5741ce59c734fa1268cd5d"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "c5ea4e267921298a6c97c81d49db96727baa418d"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "77c9b4eb6932758eb8add5ed406c08614b28e50e9b54fedf3b739e1a832e5ab8"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "d2a563bb6d5417d593baed3ea1811012bb05b162"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "5120622ff53971f4edd5e594b17273e5e67f8e84fc01262abb9beb0a20f5bf64"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "503f11517a0edd46a2d004a648377054a5f3e550"
os = "windows"

    [[Hwloc.download]]
    sha256 = "366c7573099e98888b7ffb536873c696ab7e0674c41b431b734204b73388adf0"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "d49bb97cd6456ac2c36f3ff15aa35b3baf14ebdd"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a7ff92be00b1bf58b80a6b78a4ff5cab985f8762a46a5bbcf4f7cbdcd5d995c4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "a992728be655329d4c818794cac0383392595566"
os = "macos"

    [[Hwloc.download]]
    sha256 = "f58dd9accd1556b0f56045ae7e7d53a188585c5715fb88cc3dce31cd1db82028"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "9d7fbd9b4f7c52fe3ca80084635b860e5583f378"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "0772bdde5f898dd74aa5d1da9d1163ee8f275fbbaff61e6b40e4c3b464c9cd8e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "51ca56eda15ffc13caa1bc97cdb14e5f7d03eb37"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "ddfc74228e6fa183e051bdcd336d4815046477997cc47eca7194467fd417ecea"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "1e6b2dc39008560a9c3cde7093bf7aa948cbaefc"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "3a2d29fba25d7d984f6c9174aae3b8c6fb7f6ec2a78f6b7f15d9d036d237ba40"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "e88b7057e4092b969481f855e1b0806efba12f60"
os = "windows"

    [[Hwloc.download]]
    sha256 = "89d946cf5d35cfe629b4864fb7af043009dc258eb7b68269a72b7b8d689c1a89"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.6.0+0/Hwloc.v2.6.0.x86_64-w64-mingw32.tar.gz"
