[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "f8e267c6e24f28e86faacd13353eaf4d165ce02f"
os = "macos"

    [[Hwloc.download]]
    sha256 = "6b22eacbb7edcd20a13e076d1ff89f9d539548dd239d826b603b3575fa2f21bd"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "893c027047b76dba7c5c42a0b6eac45f8c5fad5c"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a65661ed666f49c15983f9174b81d9542d520fa9a6910197acda4a57bb9356db"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "23758f52c072d5481cd6d317ab686318fa3e4dcd"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "fdf5694d959baa336202976470aa930f290e1e472b98be4384e06fe1c0e76a05"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "589b279d1966c8318084b16fa1798948f15534b9"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a072aa8bd8bf936bd7f87d867169fdc789b0366645cc8317833d8644009d9f6e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ba59784274adbddf883195b1487df944b01be057"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "4139aaf66ba0b5c3aed743ce62f8feb7ee63cf77dae60f4673de103ccc656f93"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4841558f48652bf7590c913c12b38d86dda60efa"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "6ce640d509e91e51fcac1387a261ce5f389c7f09f90d40f4a8fd3764929f3059"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3b78a26f1985280314bb89b278816ce0b7201b7a"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "940b223c9cd703b5f67eff0f04180ff8ae1c94314071d447bceb9e3729ce84e7"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "e0e398d57c3f521a8c8ef2a2f28e035ef078b994"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "555a226e37da917699e36c555a514c82e0e6f4fdf92872fec44003564afa07fd"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "10c1e75e619d8189aa17df41b464f61b8e15c40f"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "f32c02979369f9e16b48fe5355ad9f8a4002941daba882877d4582ca994d63f1"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "7b89c86e73956dedf281e3a0a4b1ee457532335c"
os = "windows"

    [[Hwloc.download]]
    sha256 = "0b82d65a650801959abf32f579a12c02ec461694a0797522b6ad556d4d5c265e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "23171216548bdc38b5a7b5da8380e328a55a1dc5"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a9eb5157f9a3c0973adac414d6a09c3df17fe4fe0f93242d0e623acb78599ab1"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "e6a27ba0205259d30cf1e58652c11316cfb9fef5"
os = "macos"

    [[Hwloc.download]]
    sha256 = "b98b6096e2f9296bf144f52387cdf63ecf87541004a1f3e46c91d1d475f04e36"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "ad1a0e8c0f77dd0df5171d02017a00ce4549ce22"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a491c51c8085d8865575e8d7ddd9b8eecf958acd056454dacdeab6c2e67b6d73"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "3e03524746712b1a35b2981c22748341c5076e02"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "2006c2812b50f707cbc2ddd936ddb5dffa925fce9a4ea1708dbdd81b69942c71"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "7961ce142d3d270cba74bacfac3bddb20e002314"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "2f7ae6cee7e78f2d39281c43357639c4343282c4ef6adde5101abee74d793348"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "d451ea5f29be2a66bd28f7e78e090b8ee681975e"
os = "windows"

    [[Hwloc.download]]
    sha256 = "79dab365fc8d94507645ad2c704095c882facc71074cdef03f89f22364468237"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.10.0+0/Hwloc.v2.10.0.x86_64-w64-mingw32.tar.gz"
