[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "efb9c508dba537c8cd8154d20b86295149449674"
os = "macos"

    [[Hwloc.download]]
    sha256 = "f016323760e9a0dc82ee1e7ee3ab94abff0b115ac578545c49e1a1fdaa1f2154"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "3037c36c4f8f226f0e7123fa7abff5462c73b962"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "eabbf0de64ff006835fb9bfb248287ebb710c77e22be294d2ccda7eef5c38a1b"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "9370e80f6e3546f8412f069e0c19957cae539075"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "b1246d795ff086ef7d32abeceb2a4815809f52e4d1a90b722ce33b46b3dc00cd"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1cd2444f316ba3c609de585bd6a6a34136c772b8"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "84377886eebdccc4e55d997a0fee1c2c9657f56f3703c2ca0dcb057c955bfec3"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e1f5d6fc0cc1b319754a4613dca4e93cc7bd9125"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "3914147308cee14c3633d7dbc4bd520daa523ee1f0c6cf52de01b601a510cecb"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "717609cb51bb2d3a6c27ef5ac7454f51d4bd8fc7"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "19b06f2bca8447d7625393cd5d108f3e49ec204229c00a6beed4d9529cbae5a6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "323c6ddd753d2646c04cf49d0bf287e1fbc1abf6"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a9bc4f13910ef8a07e00c629c36689ee9d67f2e433395f05bf7e5ccffbcefb81"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "b565bb2af1956bbf91c1592a68a2af6ac1c82e14"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "5e336443a361895d208b8f1a9dc45666f2e1e85845ea1586dca15bd5a2f1ab44"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "ff2817a347137adee4794980e85bcf9a8b91743b"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "8fbad6592d388225ab4a84d9ee9087979b74060c6ede103d666277a21b9dc332"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "b013cf08261c34e551dc838f4611e3a4f52957ec"
os = "windows"

    [[Hwloc.download]]
    sha256 = "66608eda5ef35e74e90bb71b70714ca2a0329a428995e272cce261201c3254dc"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "a7d98984ee2cff8bcfea484bfa5c1eade21ce72c"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "07db0c9b98c1502fba42d3da001143e68493191ac81a7644e8d416bbdad9a87c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "c08b327affcd1ddd02e8a0f6aa73a85ab4cce359"
os = "macos"

    [[Hwloc.download]]
    sha256 = "e8300e11b5656d8ed57b6ef5149f3fbc3a2379d102a83366b76f7371aab16ecb"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "c52f9e3c8ab578d5db3ca06eb66d2d71a6c4a180"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "0546f6d0f2e43caaf718ff0ff772379e67029eb08f3968e411498551107883e3"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "7af930f988458f1e961e934e3330bb6fed5b7ec5"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "39245f8ce6e7c5c931df76cc53d639b9bd3cd59a7080848dc01a54f17b9e31ff"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "c424c0ce04ca4c88f5dfa15cc26988c88b7e7fe8"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "3f2db17d4373bb950e66de075479174325af6f1cf4070bed08a8b11eecaeba50"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "471d348ef784d2953fd33b3e8790344d496008ae"
os = "windows"

    [[Hwloc.download]]
    sha256 = "2fe38675fe709c99baed81002636f32fea1beab406808544c76985b98549e7e6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.5.0+0/Hwloc.v2.5.0.x86_64-w64-mingw32.tar.gz"
