[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "1f05fec009c64aefd416b830a476119f641393ce"
os = "macos"

    [[Hwloc.download]]
    sha256 = "333bd50abf7dbd9a43253682cc65c774151849fb748a6dc6e7e0381a0d10de97"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "ce3bccce8f105ed13855a995913dbef4e4cf65a1"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "f9563978a35b3167c05995dfdd1d784db598c7f84394662634873834015de156"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "91becfb41aafaab104e967f513ee338a94a751f0"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "3e216f76456a741ad1b17b099266e246602289e844cf978a243e23fcee18c249"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02a7d9e9e307a51771299df44fa7cbd1957d294c"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "af9d1fffd14a71a7809da5a72713034a3df95e901f4c01bfefef6e28a5013dd6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cc155d6c8eb01a58796cc9c2487fff3fe7febddb"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "316d43a4040f1cc4340c5cbba4c3476e2c54e1421e24c5401b15041c0c9623e9"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d96ebe77df367ae32f27b1b3087f591bfecc8e8b"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "6089ad6182fb5593863492d77a939acc9b358effbdbc7691350801cafa5a49b0"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a7aac14ca78de22455cf2b206101ffd6c14e01e"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "478cdd11cfe791951b3b904d2c5655aadb681776596acf0210dca0853eaf0ca9"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "11f35d145db6e2b9596597c57f6a3a51f9816aad"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "58b698bc9ccb89de6424a96e10992b6e715c2b09a5fd79742180e3e0d1a1ae48"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "ddcb2efce8e23416b31c0f83eca5f64b4417e873"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "f463a81309ab86c3416dde29856eaba1a91ba126c9315c93a6d7b52559a27e97"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "7458caebd4a6fbd89c6a1d0edafce1e55e1c333e"
os = "windows"

    [[Hwloc.download]]
    sha256 = "e2f3918ca27c3468140bd63a6b4d03361bee15345cf4aab55ddc4e18d33b95a7"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "ef8de3ff51c8edca2ce1c12e281d9dec071e8a29"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "b606df49b9f2a50dfdb31ce0c27d7a211842bbfabef3884b578f7906053140c4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "f24f39b276d6ffeae1df99dfb3369df9294cd43d"
os = "macos"

    [[Hwloc.download]]
    sha256 = "a8bb8da5f6e113bb68b56b31fc227d4b09badb9da9f1c2531878f5fb8fd7219e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "6ae3cfc973b59c2dc2c0b05d6f6f9e86438fd94f"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "8b4d18978b41b82ea0ab6085e4c81979b57b3fafa7e07e147b8d62c31bfe734e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "b51e6a952563fed905a83ce6286e403bdaf64aa6"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "1a61094cb586cb07e703ed3ebb06825e82105875a401c6f9875c02137c614d34"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "9e1d91461f6f35304c1272adcf513cf6a5c446f5"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "30ca52159861948289bfdc051d40230035d43e6151f917dfdf8fb8fcaa8c2d3f"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "d6ac2a3eb99b6e403443eda70404a3db627ef747"
os = "windows"

    [[Hwloc.download]]
    sha256 = "fb892dc982289788f43b11a64791ca52e7119fd45e8f7a4e9cfd6e79f12e8ecc"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.8.0+0/Hwloc.v2.8.0.x86_64-w64-mingw32.tar.gz"
