[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "9443e23886d8150cfe8c78fd204729723859d485"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "fc1845607943b27225a5e5e70bbb06b5b2ebac9efd4f30e12a7119bc30d3bc3b"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "798ae35ae77aef67b411e8843d28bdd110358f93"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "55d0eee728ff649fa4738fdfef384ce412fbd91223a85e4d5a5e56cb2c71521c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f1ecdbe15de933df97b5aa8a854c72853594ce04"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "8930f269256179519b1254beda19ea37d27393b1c62d81192e09ef7adcf4db4a"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "76bab8f19d6ea3ec1ec02df1f399697a3edb46ef"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "1b6f952dd564e03c34c0151bf995005b8a053e81518434e1ec494ad4bd7851a3"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "4345a14a0fa22d35ed4dd5ca1d3c8f038e0c10e4"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "c5049a8da049eca262251b9acd99a7d5d3965b650de46d82c932e5feee2fc989"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "a1e6f3969a4a7217d8abf6b138a4479f7a00d6b3"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "71c453498c075d5cb3fe56481b02c7542a57eeb1d0819f330d229c39afd70c04"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "526ca388c397485f11b24f4e97413f637ebbecbb"
os = "windows"

    [[Hwloc.download]]
    sha256 = "37749638ce6c92d7a70396f461585bb9edd5ba1984295d9a907f02c2c2e4f1f6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "8308b49c356239597aff208e7ac4beb545665682"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "eef0af7e924b7369486b9e40c735853e70e1ceebe79f40fd15ef12da3280d8db"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "af4bb6411331655ac9a79e45154f261ea383c98c"
os = "macos"

    [[Hwloc.download]]
    sha256 = "bd41e894ae15697f9b6b0696076937cf53bc5b33231d0c87495645018dec4c8e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "c321a145e3aa4acc8661b33bf65c060168b83c13"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "01d38e0e60252a969aacaf28c3085707b82e9e27d52c8e7a1d5b825e0ca8fb54"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "dccc16e3f632bb7996c4742ba7b7e8a38383c073"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "f71a39d488cb6cf74dbf03c4f6419ece78be649828c12a3d183e5ab1b34b0140"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "ec08b626a2335acfc757d8a85e5383dae8adec52"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "cf9b7fe0f876c9511b0766e0ad0f4897c6d937cc1c895bc6506823215c56fd85"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "aea64ea11b87da17b1bff480038ff992b4a0ea63"
os = "windows"

    [[Hwloc.download]]
    sha256 = "d348e321b89b41114699722e86330c54ca74d3236121a6a945bc1639290a3b15"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.0+0/Hwloc.v2.4.0.x86_64-w64-mingw32.tar.gz"
