[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "418520e4a19d9fdd8bb914186b23612d17230448"
os = "macos"

    [[Hwloc.download]]
    sha256 = "fa9faa5376aca22b48a203510432746eb87d504aaefc6276abb3d158cfeb4d10"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "bc4a7086fdbfc74c41e02097e062aae629dc2bba"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "9581c79b0fd4ef76b48e5014aad549c89098c6be18b2507869ad3bb2f86a9d4f"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "dd0c59d82849871cdc40ecc74a118ba5e03b75ce"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "3e147c5496a631fde0248db42756008187ae99467907536aad50e841d39708f7"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "576552303e8197a485738d6169b0f39b1e1b98d5"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "ec4bbf8a76174f3ee682eec25c3c8d3aba42185e6c9002ab378685aeffc3b515"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.aarch64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "afe41e7439073098ee1fddfb5969e770422926da"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e521e789b4f8e792fd162717e1b71c3976af6978edb9cb1680f07519a914c2f6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2be49203455369ea72e1228ad67052a8c2989db0"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "5622e3fe0505ca0e6a0c03753211ccb9e0d52844568c917505fde613cc7d32b4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7240f12ff0046036478a7be92adb66cdb14fc905"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "eeee7c5c882b1df34248da42f5a7db77a87160a210dc00b6935675f1a1a18d2a"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eecba825e282edfaa08adc52b7f6b8794a81a9ea"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "37d73f3d69210df688c912d04f7d413b7ec397d2de04305371e551e29ce764ca"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "46ebfe49ddd43f7ff591d2937fec1ebed46d393d"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "4fb9d006cc56102fada74c65358b2d0d6dd98afde24d41bbcdd78fa9662d0c6c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "f9a228acecf2d50de94026b7d425b8d98b2b8e2c"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "12c7ec735a59459638b4d0d903844c6cd04be99a57e18dfe33362a86d50cd75a"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "9637f16d53c7360c7770dd371d94997434f2da49"
os = "windows"

    [[Hwloc.download]]
    sha256 = "3b1b16e8eef66d59f48d8085893d3711369a03c27af2c08a1094875f82415b8c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "a5b3dc4f44d4a97e522f37ab6ab19640c931ec16"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "6e56bfceeb54cf8a9da22c5bf555eedb519ebc4107b7b00663c4349675f503e1"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "f1cbcae6891abc21d90abd4df2b59daa16088f80"
os = "macos"

    [[Hwloc.download]]
    sha256 = "7cdf8ab320fafe04e70ec0630a84b2d942c1cec09f0b97ba4310adaeecf5f880"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "392724d73adc5c202f4cf8fd512d8167a4a61002"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a58c722e666a5179f07a62cbe7dde605bb7e4f63a52aa0bd85bd3ca1e2ea9cad"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "7f72f2de2838d55dfd48186c83217cc518e05990"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "39c80655cc1bff4a85bd02e7abf65113097ae74264a781563a97904b23be1f9c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "d4dc44823490825878e6c10c7efd411771dc5653"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "6ee8464f8da2c727d35b5c9bc539e032290f2b533eb432185d57d90c34d798d6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "82ad150a8954cb05b42269f5cf55f2121c300081"
os = "windows"

    [[Hwloc.download]]
    sha256 = "b458aac9b7bbd3728ac3288efd2ca69be92f322487fa9c44ef842a60eeceef85"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.11.2+0/Hwloc.v2.11.2.x86_64-w64-mingw32.tar.gz"
