[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "c1d10aa0b76a7600589bf9dddce8c444cf4b3160"
os = "macos"

    [[Hwloc.download]]
    sha256 = "2ca84ac37d8401e5ac4dda0d980ce17a6d77657a03d8b8a8b76201c7bb9bcb0c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "2016ee3965221c6b33d57bab80e60d7ad4a354a0"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "3476bfca40d9fe8ae60ddd0862eeec45ed05577826cbdffe528da0c5e14b8881"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "e04b41c7ce80d4ef86b9378b9288a89229c2f54d"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "30b9b54f459e2d67f684e763074402f02db9e4aa1e4e1580698c7ba44d8e78ff"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "761acfeab2104e968de7e289ce9d393947c419a6"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e8afcf85df12ee5ee7fe1b57589e1a2b7a5fcb3678c755dc02695f46b7d9fb58"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "21e3d1355e8eef9fadf4f1913d76c24f881928e3"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "74263d6e7dfb473097355cc8ce419e07db0ddb446c4fc2946c4210b1e526ac98"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9f5dd4fd5db313acce6336726ee9448c855e8132"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "544d2f7f4fd1b48fd9f0c13e7172f4731f727324fb89bc6683306d15d0b2ee68"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e2e635e16ffda8668a12a21158578c6db681c231"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "d8c4dd1ed5c547608b7b18496fe1f8761b6a8bd8ed3afbf79aa960088c338179"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "768849037d4247548706277f20ccdbaa20bfa742"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "6336e29779d95fedd68929c32e6698e9eb3a5ff09af34f576d97ac399325fe9a"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "384aff64d38aa3c8827f45ec8afa9e37166eb46c"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "fc1bb93313dc8b053e5ffe2d75ccd6e877f1defd29d800c891593c80adc92d62"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "77f73a7535fee28016adc723ebc612156aecc237"
os = "windows"

    [[Hwloc.download]]
    sha256 = "b1c9f57a8dfb0dd2fb5b05673ba584c358f78ef6329df154d6d78ee43ddd48b8"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "9dc39546ac1fa901baab0885f7f8464a96c7175e"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "b5919d6c7fac0e8a11a70d3054fe3cd4cff2bf0dd2279a8ad4e0b70038a313b2"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "29188c8202de2313fee0c55cc527586c4ede3046"
os = "macos"

    [[Hwloc.download]]
    sha256 = "c34832fca2ec4329639b199bdbad354e117487f7a7463d5227eb5d34bf325f02"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "aae9ba66be9f6bccbfa324bbab4fa317b676b9d2"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "1a52c50b488f223cad723975a1d8d7a708c9a62d941244dcb9bff1d49f6075df"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "15d02b8398d19f09cbdb30d648f746d6dbaebed4"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "46834ba8b3ae9bdca36a6bcab312da93a50c1534d31bfe20b2ea1ba7249ebe11"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "3eb43ad540434040b36800053c7e4f3cdab41c71"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "3ba884c321984b01117fd585f3b6ca44b226ec8e56e541da1029498f8ee2e545"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "85e18cb8eb26feb3e4f841dc7b53085b52ed4765"
os = "windows"

    [[Hwloc.download]]
    sha256 = "37d6e7ff9278f4f794d5e517063d980dac554ac4854f17b47335ac8c06d04fb6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.7.0+0/Hwloc.v2.7.0.x86_64-w64-mingw32.tar.gz"
