[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "46869426819333690fabb1012933375a5006970d"
os = "macos"

    [[Hwloc.download]]
    sha256 = "e45327b155489291377b724a13f193269984f3f1a908b7fb60cd26bc4abeb14e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "f98e545059c80c6aa29212cf843e9de086ef80ab"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "72f821f5b3b9d9db1a9c7a46c07df3b680aade2d2bde2d7b055daac4b924d2bb"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "d47e520cec61b75409717c92d07859cf062a0724"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "5725025967b451c66588daf893c529aee1f4ef1c6025909fb72d9ca355641e43"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "53a0a13ab7fa5758ae38dd2725a1236274934d9d"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "322e21a4bed41d96640d25d15218c3fd523998b9c45f3e63a469d44504eaf786"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d22e54324fe8f4084f895ccfb5c70d37528fb70"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "6c28a20b2dd446f8963f9cd479aa0d7f4d6ab9092467ca27a8ef6a57834ab96a"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d203024d1b5412ddeb815585bd3dc84d72fbf4c6"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "7c59f32bf23bbbb4c68c9aec4270a7116474bb29cad697d14ae9f6b3da4c0a9a"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5ec25cd8183ebfb701b381cff2174b5b16ade9ab"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "aa5a76b11e97088960335457a8fcc7c9ed4884aa3a07ea7084e186ba60dc1ba7"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "db9afb0ff843fe15db718d5cd0bc1ee2457b21d6"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "487c3cca613f45a5feb5e463036a5b5a87745259d0a2a788b92705aec4e2adb0"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "78b27e38d26df0ecba58a6b92e6d04db848a2a7a"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "86edaa8b27155dd654301409cae38312fba0ca46345634958eefa5b7559c63d1"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "8c3bff12bf93682dc8a2de93feb1240de37fbd11"
os = "windows"

    [[Hwloc.download]]
    sha256 = "bfb41840f2359c1cd374a81573cfbf22be5923be3d77876aee77e581ee6733d9"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "cbf6d8ec1012d0dab4474552706fa3809def70c7"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "758d990f772c6e23a142145b9585a2a795434f61fc68780fc98b94b39e41e582"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "83c0a0d3b98258ef8674f86df05883118f6f2a30"
os = "macos"

    [[Hwloc.download]]
    sha256 = "8b3c63789b1799f5a120b69d51404e59db4962557d46cd0df14c20c422d7ae29"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "5374e3d088a155402b8df391d7adf6ebc749ef9b"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "74886633d9b7612f46b9ade1c00c0aa2cf75a0bb2913865df2989ffd61945c42"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "9eacb5bf2629042999ee21ee12ba6714cd366533"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e1ce7bdc278578a9adf4a377f1c999130e43184c3bdf0798517edfffd709c570"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "24fb54aa27debf13d15c49bf80dca4d95340e804"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "38ae94361cb6b27a83f013a55639306a658b21b8c0031b9bdacbbb3152c72d22"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "6a1e144019038ea70921eb4998a7b79b15a52a41"
os = "windows"

    [[Hwloc.download]]
    sha256 = "dc292036a66fb7e308f4589e4c6e5de8f91053c24b24ec9ef177b1e5cd1e0108"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.2+0/Hwloc.v2.9.2.x86_64-w64-mingw32.tar.gz"
