[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "a5796fc0c827dab12e5ca4ac2ff5b8fd48e26c1b"
os = "macos"

    [[Hwloc.download]]
    sha256 = "49a772fdc43948373d933002bc851e36d422050e815943c24bf32eff72dbaf3c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "5ab371c9b910591cfeceb846bc854222aeb93650"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "adea1a182943b56f37adac3495f6c8ba8a4a5de42e50d30701e27a1bc85a756c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "4fb5906aea74c1460e43f4f89df7288d4dac47ee"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "619ecf5ca8c0aacee81060faff6def6cb04d71846dd1727cbceb95695c238b8c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "4f10b52bacfa734300e023987f7372698c4d59ee"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "ae0fb8b9fbe97836ab118bf1517a58dfbe734cb5b9555bb4f5228f2138e4b5b4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.aarch64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c7214ea898a335ba23436fd290897ed426cbd36"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "03e40fad5daf2d56d58272f63822d0c67c04d28cfb38fa0d2f8338450ce0b4fe"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a3df7f0c19b763cbb801a65429c29d678ed73f19"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "017bd5c35680658cb6609d4bed00116c2f8f1f3c25dd05ff62aa8aa1e71a9ab7"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b6f6281c6632e553e48e7f85becd3510e29253c"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e613750d34d448abd6721f0c93daaa165306c5bced5ccc8bb6f784f6e82af273"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a685fbb54f4d305a3b70a63e4bbb22c35e29c9d2"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "c544f903d3b5529f83fd2109ee8c8cbd3c8194c13d4c55b19ea24da3e27f9c55"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "945005506057d58c6e9ade42e0270a194574d1f5"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e8fc1d17839159018ef88c3925e89c45cc2078323a2e1d750aecc93ecd0f9da5"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "4347c99e4ffd72b538f5a4dd50f02c0a11394476"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "01fa959897d7867df701c7860ca5079e22fbce1770a2cd931cff59483cd5274f"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "21a6852d6bfc4c401857df72021fd5c03ab7fff7"
os = "windows"

    [[Hwloc.download]]
    sha256 = "fcebb014fac698d46103f85303d5da416cc32f4a2fc9cd52b3e45e8b911254e0"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "cc8ed17172a6e9b613ac28234171a87ac0464587"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "22fbdbc112dede978027720019dbde99b7ead44b0b671206fcc52aadfaa837b3"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "riscv64"
git-tree-sha1 = "7bc97e6fe5366a5758f129b48c3461eb65439a55"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "3784f6e92eefda8d7143fbf83d5c4df4ef9a7bb70e64c059967fa422c873a25c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.riscv64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "11ed2059880e277172fca3437c272c8041ace203"
os = "macos"

    [[Hwloc.download]]
    sha256 = "e3fcf7538f8ff022c097bf83461058eade3cb7e637e9bf63c0dc537d6754b678"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "55b3ef68fcb01cab93cbe76e7b48e5fb802a9ecf"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "2d32df8482894585e143cb74ccca7dd6764699deeb51dbbad495b5b307f5528d"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "3026fb4d165a1b2c90ce3080ac8b61a5a720c991"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "d0d895bd9f4c5ffcb5f24a687490a2c027ca6585b531c9a297642530f0029bbf"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "db0b88902944e1b61b32a6c6d551d04374c5aaa7"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "21fefd8e99db26fbbd1ac4fe6cb931e2a847f376fbed9e22bf9a08d560979a20"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "e4e2132ea0ad95b18fffbdfce2012b6debc75ae2"
os = "windows"

    [[Hwloc.download]]
    sha256 = "5b13439e257e337ec41e5f4a54c6a2378795e04a63bce106823d37739f8d0bf9"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.13.0+1/Hwloc.v2.13.0.x86_64-w64-mingw32.tar.gz"
