[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "3d921c0d99f2b3728718836da4cb0a41ae3f31dd"
os = "macos"

    [[Hwloc.download]]
    sha256 = "f438c926841b3c1c767b99d5c347160e10807e4ba5a87f46e625373d35ba2c0e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "ed6e7764e02913029c7ccccf0afd4c08097beda1"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "9663dc824aedb82ca71f3d35de1a6f66cae89618df9c4feb95858d7484989b69"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "6ea89e10758841036a80d406d41339be047e1a3b"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "2e05bccea5d20340bb8dea6c5292a82299ca63bcc9c922a553821997ef7e378f"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "9d82a0e4d039956539ec2f13390c85ecf8dd41d6"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "63078172261c249bb9cf49fa5ebb7f4a0d96a54415f94d3514ab4be91729d809"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.aarch64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "302b4c77807cdcd08be3967e4dd07bf2278add5d"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "2f42771a6d43d969ead3f1a908b1989b4b30cf5e0c4e95b745393b1dbca3ad29"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "622a672e957851ed5672952501c74771be0e85d8"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "5173f6e814931a1f4f15599a9bc10015b522c6026a380e479a7706fce9e6d042"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be0b4b437e5c3523d4f97b1de2cdeb6e3cd3ef0d"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "120f0b6037212cdd936a9186a5a142b23242b58fd9b64e9b0851d68dec9841b5"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0150bbac2c8ee05a539bc9581fd2d71f1387a18a"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "58b55bec6839f42cd38a22c642d8020123c486cd4b8ba751cc8e9a709ba143d7"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "d3532ccd799d9067aa4d0149cabb8a045c240201"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a4c109a56d0bfe6310747788ae300cf2b4051ee1caf17ba63d3226eaacece632"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "477994cf3654b32522b6da59b74c6fc2dc8642e4"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e53ea534583c9aae78b0bd27509dce5c46ea8da3e2860f5bd9d6286a26395af2"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "46dbb752aecdc54dcb0c96ff966a66036ffd6aa1"
os = "windows"

    [[Hwloc.download]]
    sha256 = "d1809b6d7d0269b0f2c8b2b1a59372e7a7b5aae3040ae4beec6a038d303d018c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "21ad7ef13c3923dd33dc3df8bf2d5ffcd7f2118b"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "2a44bff2b34b78ba060893cb7794908bfd5bd376b1aa07e57f2fb4b995af6786"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "riscv64"
git-tree-sha1 = "4a0e939ab24815507c15525853eacbc96d11f919"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "594d63f5465b9070935b5d078190c4680e8b5ee9880d6895d2d410c76cddf17f"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.riscv64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "67d424d25c1472f36e28a5fd6e72652998e6f778"
os = "macos"

    [[Hwloc.download]]
    sha256 = "7a7951858dea943c056ef9c1e7d082e03be8dbafd99ac066ae45873c62c93148"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "c9b8f588306f556fe6a81910916832bbd3fa9eca"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "98caf23ffd8521492ca788dc11658c6c45eab2d1654d70fba65258bc983b3192"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "0bd9470f7e3581b4fc44e023204ea7dbf14d7193"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "53e3d11984c90b35e511385de1689612b035b40a13fa12e13842d9185a379bc4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "b1b304c47a11a5b718e088d6f1ac0cd512c2ff71"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "3d5e8010cdc409b8a034c8de7b4254776c6509d737548e52910a891f8aa6a39d"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "586254da9d38c55e786a82e5d1973e8619685b2f"
os = "windows"

    [[Hwloc.download]]
    sha256 = "1c1fa4ec8c8f42cbb2e6a4194467967abdb3baa0c161a4d1703f13bed4fcb0f5"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.0+0/Hwloc.v2.12.0.x86_64-w64-mingw32.tar.gz"
