[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "1ca6f87261aa4ce8230c5cbd2aa2d7b9e020da56"
os = "macos"

    [[Hwloc.download]]
    sha256 = "c7bc6f0198329ac4026b0e454806034fdcdca4f4457ef5b7ae31c26620a12968"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "774b6d59725e0e8618b532568599c3f3b5d8211b"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "5ceb32849c51ecfa96c3a6171e7aca3492ce46f08338509a04e5d0cf8fa9a559"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "615d6636777c73b4a018ef4e948d9f4f6cc5e189"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "edbbbf865d58693687e3616a1af4c3b0b4fcf2ed0fe1a40687a9ad69b59481e2"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "611d0b44537d3881517738f08b9bed05ca34c4eb"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "ab9ee2b5f0e1a5667b2390a4c6466e05eee7ab1afb7fcfd0f48e7bf44361aa7e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.aarch64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f1aaedee0fc9dd3815337301486b49fef0a12777"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "f800f139a58d72f92251186b4a71b14e18d8a3dc7fd8ce96bee507f3207f2896"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a9b249a9c774eb1d993bd8402eb4f18c0747f1cd"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "1b57088f3c1258472dc53344383eec8c5d1b2d774601f44440927407fb5f0550"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "14972472be1d331351263851ad4cf70c0aef511f"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "2eff7365d1db67e394309b00972afe5bca5d50bf6eeb6666848abee8fd9d60f0"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "880577f1037c4f29bb965d054960e97fe7490b5d"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "cfb084d23d55c164a2b24bdaf0049db221ca9c66d6e8f3488ce78b3ad3ca89b4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "81574dceaaaeb613e5b4b39438b2980d32f12e35"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "eebf8ae30fd607f4bf47552f0836f2489c7d79143018c54c25340cb56148ce58"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "efed18fa6f9efda04c725437b6d8b0d3df0f927d"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "23a6e056ca3505c6914c3d91990a7abc7c4e39e11b1fa7492d9bcd0cf90342ce"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "a423f67e973c6b5a1b600e13f4d1fdbbb94f8f15"
os = "windows"

    [[Hwloc.download]]
    sha256 = "634f51a6a523a2634fd36e318048f4690a990c645bc05d09ebc10b288650566f"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "097d6d9e80ec73e84ed41df54c64837afdce6143"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "08debcfa5fdc31d5c8a13f6a7936fb2a51660d7abc1131a3ecd60b9587aae6d3"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "riscv64"
git-tree-sha1 = "60100936dea59275e5649927863a759f0b5c1fec"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "82b5114724611f8930625e387fc6ef09c31baebc3790c9fc0ec0b5903b51ac02"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.riscv64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "f02be6a062d6cd1de687e249e020c6dc1cf21753"
os = "macos"

    [[Hwloc.download]]
    sha256 = "b18ce450d0f8182b36396690ce6f96f444c9741d7c1362b6a8c35f4cc1c1ca4d"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "cca0c2dee0e2a3c254d43ce2b2fee025b65b9ff1"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "537bc15cc70d63b3272fc97771ea19402b31544e668fefaa0a7de2c73e3b868e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "8995fc01d71f2a8f426f0ee6d81e8bc10cb8b4a5"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "427767ee26d25efee3fd0c1abfa23498b8193f5cbfbaa9e2c01b4a26dd392f14"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "fe0b157fb19da6c0273b95ca47cff91635e975cd"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "710fd0fbf2e31ba7bbb4bb44262c59fcfa4bc6baf4fd095320052e58b8e9f305"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "283d089b32d47e60c7c4b2bc32969204ddf37c7f"
os = "windows"

    [[Hwloc.download]]
    sha256 = "81c4fb45cd26602b3efc66d44c4922d7d57598bdffb6d5b7fbeb8e652715b26d"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.1+0/Hwloc.v2.12.1.x86_64-w64-mingw32.tar.gz"
