[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "1c3753ed9a800ea4ab76b6c0f2d35f1014813c3e"
os = "macos"

    [[Hwloc.download]]
    sha256 = "f7519b52984fdf8ae9d9585b89e5776085334f9818c41fea8be238ba45258ced"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "f5b64701f3f8d0082732b8aaaa19d5dde5a92907"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e3334db4f3845160c081d68221edf409d09df83dfe05b2dfb89e8645d37ef469"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "e3e20c7c1e9442a475edd1e1744e5c4aaf455c96"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "561aab43728016bde417feae630d56f6fc6c9d21a0ce5f6f944444fa8cec6ca5"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ee2d62b35f43445f1645038455291ba3d9435d20"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "05ad5979be18e856f1bc794fb71aae8ca2794317a5cfbe3e413e16559ccc25dd"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fcb97b02ceb15f2b0650d3c555da6563ab2d6e86"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "7b6882fe1e06166409491fee68eaf3addae38ef137afd7a0fa4fdbe02622f43a"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "25a84adb98b77e696e0c3f6e1ae20d672d14d730"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "433f514d197a2c5c2b582d199bce477adb2737e042777358f630d0d5301b5b39"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec4184c0628626c77d143f71309846230ffb1247"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "9dfeb7ff3c16cbb179a563b8955d8180b6ef7f3db2f427d81aac23b728aae0a4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "6700986b6ef0b5099950d83b857fda89e8e6b6d6"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "8d2f70907ea547ed306f7f14792b26d1ff21459c9c2b9220618fb278b3921a93"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "4ad79d028b6ff1aa6eeb314b488762b49003299e"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "447019e1a130c8bbecc022ffce65c44bbb4154cb57bc6c1de8a80f5121ab13f4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "c49146ed8312dd25f3bed056becfdd488683fd51"
os = "windows"

    [[Hwloc.download]]
    sha256 = "4188124d7d5a5c4b2fc72284f3eaeecd93da0d989b19d25c310d84c5d63711d4"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "0accba258783cab0562b01766c9660f32182da52"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "d9dd2058eb2b6e69bab2617748489576589145da737e550be80c0232fcf26020"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "c46d9965e4c9b4152e1154f15ef4120aea345fb4"
os = "macos"

    [[Hwloc.download]]
    sha256 = "69988e5b2bcb3ecfec73b9bc64af07695040bf22789ef5519036c235b7f5c954"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "8b99271067209374605472e30eff7ab9e03ce9a7"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "c3cfdbb5975be258c6b2e0717ce7edf045ede51c25c99e3b01fbfca5290eda44"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "c635d196af3bcbb89bb61f1affcdf42d960d73a8"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "aa04c9cc1d368c9d2749d32cfc3ce03013625999a7fd51a184d5e12d9c20c348"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "4f281b4fcec2ae1eeebd43e73b53658e35a5e914"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "da3df2df653263fe1f38e88c37bbe3e162f6ef0f38ef068abeb1397ffdf04d58"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "cf4a2a9443ffbdee14b994120270a70474f350bd"
os = "windows"

    [[Hwloc.download]]
    sha256 = "fced88995cb479a116f50d857eb5bbaac7b81a25fc4845d20259a7b6d82b6f1e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.1+0/Hwloc.v2.9.1.x86_64-w64-mingw32.tar.gz"
