[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "34f833ff997387256af3e5b520f3e523bcd58081"
os = "macos"

    [[Hwloc.download]]
    sha256 = "a7e3ba569523c7b58ea713081e287e6c1a606eee2ed8e9f795fe862937ce0e34"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "e8bd00341882fc5a97fbc6bee2b954eaeda7e878"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "9488a8f761ab9a1fd6e39c33ef6a9d50154135eebb716be7f5b2cd3ab88c3130"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "b0940117faeb459d9e14a2bff769d61685d899c4"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "7d885eaf0f16994f46721ce7d900a2f55c091bc5035e54f1d03dcd4b652ba9bd"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "940aa79573d25562a190c84be5536cb7b7614b49"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "a980d7be4b6ff8e209959efc064ea9b8ca7e8c8cd03400db46033bc41c1ac916"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "46813a2a09b9f9d0844027037ba7f6e38d96f9a7"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "8ff485c9b1776f6328659701f03e145190eb1fbca0edb7af079ff12ebf5d623e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd965961c7e5ddce123e8cf4457e19d0fddeb838"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "3f22819881f46c7298e4483fa0d5316690d48f1220794308cb722e64da52e74d"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0d76e9e73dd3f8892c13b13e85eeb393a9e14f31"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "424d16efe6b29c5e8c0e5cfaf7210c6728a27a1ba4e24ab036019b0a5105f706"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "c37ad34dbe91e3a6f43c7cbbe5a7d88bb2bb108c"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "0cbfeee602ad33e0c89cf7f1757fe7e116d5d65e585be2761df394096e0965a8"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "21653e2188b1c576ca531c70233c3bc8319422a5"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "0e98511b7ce1e650a193ca1c0b2608ebbde8b463b6db1c4b4afd16bafe5f2e3e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "d116ece70b5896bce324ffa8583287b79b9aa337"
os = "windows"

    [[Hwloc.download]]
    sha256 = "52b2144db31cec52d0def4fb382d06dbb299d312f249239580615ac7a0250ff3"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "df7ad45e4f2a09a40c81e6138403a0777e8ef160"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "4dacc94d78d771f04bbe92cf049c56cbc94244c324aa0599cab8d2feebc89977"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "5d09039ca211d86a5841fc76dd3710ed87b80831"
os = "macos"

    [[Hwloc.download]]
    sha256 = "0fc8ae19c032e258887babf076896cf6f19746ee623eca45f7fc107ae18fe7ae"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "c5fb0af4a1d1b8eedfe9da26f7d78d79b444b449"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "c28e1125da30b0b6bbf914c248edda465dccf48e83be308aa8d3e3247f0b0247"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "415b665230cb1bd6ee745754ad27d70658fa3c5c"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "2bd391ed9b4e35976ad83e8ab524eed83e05c09137fb458e2662218bcc10de8c"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "dfef69b89d6cf993e2830aad4137a961bca102c9"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "7c92776e508c1bcf940bbf6a257697295526f8a92d1650531d58a6fcb2bc3b74"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "7561edb9bc9f8969a28ee65cbdd512674a5dc3b3"
os = "windows"

    [[Hwloc.download]]
    sha256 = "29612f95b26a69ec053d6598253262864464dce1df63ac2041ad9087da9a015b"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.9.0+0/Hwloc.v2.9.0.x86_64-w64-mingw32.tar.gz"
