[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "520e3614b3e77d31678139cb8e74332cf7b78255"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "ee1dbb615ce41c0d66a66597e53d68c1580b7a4447f1ccab96c2d0701d1accfc"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "fa1d0ef504a6aef3ee11914b78f43c5029f9d793"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "0fd0e3b18d3684b0747c9564c8cedece9a124ad30bba77cdc71748347c5bed71"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "932a1ce7a2c3a47277748f86e3cf1eaf297f4a61"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "f5ad305bfa5552c1c8fb16b965520f9421d9ef95f450965385c79ed6462355bc"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31034f4b43af5eef69091b749e4c3a0da222766f"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "72a36fde62b42e3f93441e39cabb5fbf7918da07282ca6fa6a0b7811b16cc000"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "2f47a13d5ca161357b5e4cdb55e0d8332cb4faf8"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "3be474d0bb2484ad73b5c9398d1d7eb9a34babf8256bc848aeee2b43c8347712"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "ff92a36da17cff3c4b5ff2a08374f3e0eefe7f80"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "82cec4531bbe821895eac1feb621ef780153728a7a47c2b04cab76b1e5dddf93"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "48dcc3683eec8e006f6a24fae003162ce910e71c"
os = "windows"

    [[Hwloc.download]]
    sha256 = "0eb2d9f4731383bd6aaca68ae7f7ae17868d8b4b5c55857e753a51368551e54a"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "9e0040e0b0bf7e22b87852138dbd92756fe17beb"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "8b5de10d38ea14867acd6e0b34a21b0fbb4aa809aff09aaa66f942e294aa69fe"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "9623c056cf90fd8ef75fa2b397421ab97357da93"
os = "macos"

    [[Hwloc.download]]
    sha256 = "0e56ddb7ec7e57095166b2e9ae4f81c4d4ea8ef0846c8abc669d595f8c2a491b"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "ae9d140e64c7b783fbb8e3eba98414611d2061fe"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "7a536b8f6d113b128ce1a2f2f32da0d7ef2e36f411f6db467c4fe715a2a78e77"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "6e45cfec4e69645e47fd8ad5c298dd09ef600c1a"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "24ef3549e7d5a9354010d472ceb939cc75e2d1b4d03897724490676a16064164"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "76d43a428c48acfa824545ba18cf26da5ed9326c"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "772bee7cd06fa7d7228793b134b8108eea29ac770f3a1892df8f25cae7ac7c34"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "7862371193afeddc337c93c2c3390583bba0fe00"
os = "windows"

    [[Hwloc.download]]
    sha256 = "d4c44a35cb3e8965fa75952e3761bab96cb869a117026f0e93e993ba7550910e"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.4.1+0/Hwloc.v2.4.1.x86_64-w64-mingw32.tar.gz"
